### ISSUE TITLE
Unable to configure Cups

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/cups-wrapper#4]
Try to config with no changes, click save, get error

![image](https://user-images.githubusercontent.com/39687477/150202274-17ec87bf-2eef-47e0-9a1a-b0e62c1cb36a.png)

**Comment by chrisguida** [comment]
Wrong repo, transferring

**Comment by chrisguida** [comment]
Fixed by 1ff37a0b9f0a9e010ea6352b7f42c2849b2cca06

**Comment by chrisguida** [comment]
Also needed to update spark and btcpay: https://github.com/Start9Labs/community-services/issues/4#issuecomment-1017779564
